package com.example.a07demo.detail

data class Data(
    var company_id: Int?,
    var deviceToken: String?,
    var deviceType: String?,
    var group: Group?,
    var groupName: String?,
    var id: Int?,
    var isChatTermAndCondition: Boolean?,
    var isDeleted: Boolean?,
    var parentUserSSN: String?,
    var relatives: List<Relative>,
    var signedUpWithNumber: Any?,
    var status: String?,
    var userAddress: String?,
    var userBirthDate: String?,
    var userCity: String?,
    var userCompanyName: String?,
    var userContact: String?,
    var userContact2: Any?,
    var userEmail: String?,
    var userEmpType: String?,
    var userFirstName: String?,
    var userFullName: String?,
    var userGender: String?,
    var userIsVerified: Int?,
    var userJobTitle: String?,
    var userLastName: String?,
    var userLocation: String?,
    var userProfilePic: String?,
    var userRealation: String?,
    var userSSN: String?,
    var userState: String?,
    var userTiear: Int?,
    var userZip: String?
)